version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ladon-postgres
    environment:
      POSTGRES_DB: ladon_db
      POSTGRES_USER: ladon_user
      POSTGRES_PASSWORD: ladon_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ladon_user -d ladon_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ladon-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ladon-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ladon.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8088:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ladon-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ladon-network:
    driver: bridge
